AWSTemplateFormatVersion: 2010-09-09
Description: Create Project profile for SMUS Domain
Transform: AWS::LanguageExtensions

Parameters:
  DomainId:
    Description: Domain for which blueprint needs to be enabled
    Type: String
  ProjectProfileId:
    Description: Project Profile id for which we need to create project
    Type: String
  ModelGovernanceProjectProfileId:
    Description: Project Profile id needed for the Model Governance Project creation. Can be found in the output of "create_project_profiles" stack. 
    Type: String
  Name:
    Description: Name of the project
    Type: String
  UsersList:
    Description: Users for the project
    Type: CommaDelimitedList

Resources:
  Project:
    Type: AWS::DataZone::Project
    Properties:
      Description: "Testing CFN Project"
      DomainIdentifier: !Ref DomainId
      Name: !Ref Name
      ProjectProfileId: !Ref ProjectProfileId
      UserParameters:
        - EnvironmentConfigurationName: Lakehouse Database
          EnvironmentParameters:
            - Name: glueDbName
              Value: glue_override
        - EnvironmentConfigurationName: Redshift Serverless
          EnvironmentParameters:
            - Name: redshiftDbName
              Value: rs_db_override
  
  #Internal Project for Amazon Bedrock Governance.
  ProjectModelGovernance:
    Type: AWS::DataZone::Project
    Properties:
      Description: "Govern generative AI models powered by Amazon Bedrock"
      DomainIdentifier: !Ref DomainId
      Name: "GenerativeAIModelGovernanceProject"
      ProjectProfileId: !Ref ModelGovernanceProjectProfileId

  "Fn::ForEach::Users":
    - User
    - !Ref UsersList
    - "ProjectMembership${User}":
        Type: "AWS::DataZone::ProjectMembership"
        Properties:
          DomainIdentifier: !Ref DomainId
          ProjectIdentifier: !GetAtt Project.Id
          Member:
            UserIdentifier: !Ref User
          Designation: "PROJECT_OWNER"