AWSTemplateFormatVersion: '2010-09-09'
Description: SMUS CLI Knowledge Base Infrastructure

Parameters:
  UserRoleArn:
    Type: String
    Description: ARN of user role for OpenSearch access
    Default: arn:aws:iam::*:role/Admin

Resources:
  KnowledgeBaseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SMUSCLIKnowledgeBaseRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::smus-cli-kb-docs-${AWS::AccountId}'
                  - !Sub 'arn:aws:s3:::smus-cli-kb-docs-${AWS::AccountId}/*'
        - PolicyName: OpenSearchAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: aoss:APIAccessAll
                Resource: '*'

  EncryptionPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: smus-cli-kb-encryption
      Type: encryption
      Policy: !Sub |
        {
          "Rules": [
            {
              "ResourceType": "collection",
              "Resource": ["collection/smus-cli-kb"]
            }
          ],
          "AWSOwnedKey": true
        }

  NetworkPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: smus-cli-kb-network
      Type: network
      Policy: !Sub |
        [
          {
            "Rules": [
              {
                "ResourceType": "collection",
                "Resource": ["collection/smus-cli-kb"]
              },
              {
                "ResourceType": "dashboard",
                "Resource": ["collection/smus-cli-kb"]
              }
            ],
            "AllowFromPublic": true
          }
        ]

  DataAccessPolicy:
    Type: AWS::OpenSearchServerless::AccessPolicy
    Properties:
      Name: smus-cli-kb-access
      Type: data
      Policy: !Sub |
        [
          {
            "Rules": [
              {
                "ResourceType": "collection",
                "Resource": ["collection/smus-cli-kb"],
                "Permission": ["aoss:*"]
              },
              {
                "ResourceType": "index",
                "Resource": ["index/smus-cli-kb/*"],
                "Permission": ["aoss:*"]
              }
            ],
            "Principal": ["${KnowledgeBaseRole.Arn}", "${UserRoleArn}"]
          }
        ]

  Collection:
    Type: AWS::OpenSearchServerless::Collection
    DependsOn:
      - EncryptionPolicy
      - NetworkPolicy
      - DataAccessPolicy
    Properties:
      Name: smus-cli-kb
      Type: VECTORSEARCH

Outputs:
  CollectionEndpoint:
    Value: !GetAtt Collection.CollectionEndpoint
    Export:
      Name: SMUSCLIKBCollectionEndpoint
  CollectionArn:
    Value: !GetAtt Collection.Arn
    Export:
      Name: SMUSCLIKBCollectionArn
  KnowledgeBaseRoleArn:
    Value: !GetAtt KnowledgeBaseRole.Arn
    Export:
      Name: SMUSCLIKBRoleArn
  BucketName:
    Value: !Sub 'smus-cli-kb-docs-${AWS::AccountId}'
    Export:
      Name: SMUSCLIKBBucketName
