applicationName: IntegrationTestNotebooks
content:
  storage:
  - name: notebooks
    connectionName: default.s3_shared
    include:
    - notebooks/
    - workflows/
    exclude:
    - .ipynb_checkpoints/
    - __pycache__/
stages:
  dev:
    stage: DEV
    domain:
      tags:
        purpose: smus-cicd-testing
      region: ${DEV_DOMAIN_REGION:us-east-2}
    project:
      name: dev-marketing
    environment_variables:
      S3_PREFIX: dev
  test:
    stage: TEST
    domain:
      tags:
        purpose: smus-cicd-testing
      region: ${DEV_DOMAIN_REGION:us-east-1}
    project:
      name: test-notebooks
    initialization:
      project:
        create: true
        owners:
        - Eng1
        - arn:aws:iam::*:role/GitHubActionsRole-SMUS-CLI-Tests
        contributors: []
        role:
          arn: arn:aws:iam::*:role/SMUSCICDTestRole
      connections:
      - name: mlflow-server
        type: MLFLOW
        properties:
          trackingServerArn: arn:aws:sagemaker:${STS_REGION}:${STS_ACCOUNT_ID}:mlflow-tracking-server/smus-integration-mlflow-use2
          trackingServerName: smus-integration-mlflow-use2
    environment_variables:
      S3_PREFIX: test
    deployment_configuration:
      storage:
      - name: notebooks
        connectionName: default.s3_shared
        targetDirectory: notebooks/bundle/notebooks
initialization:
- workflowName: parallel_notebooks_workflow
  engine: airflow-serverless
  type: workflow
tests:
  folder: examples/analytic-workflow/data-notebooks/app_tests/
