AWSTemplateFormatVersion: 2010-09-09
Description: Enable DataZone blueprints for project account and create policy grants
Transform: AWS::LanguageExtensions

Parameters:
  DomainId:
    Description: DataZone Domain ID
    Type: String
  
  DomainUnitId:
    Description: Root Domain Unit ID for authorization
    Type: String
  
  ProjectAccountId:
    Description: AWS Account ID where blueprints are being enabled
    Type: String
  
  ManageAccessRoleArn:
    Type: String
    Description: IAM role ARN to manage access to environments
  
  ProvisioningRoleArn:
    Description: IAM role ARN to provision environments
    Type: String
  
  S3Location:
    Type: String
    Description: S3 location for environment artifacts
  
  Subnets:
    Type: String
    Description: Comma-separated list of subnet IDs
  
  VpcId:
    Type: String
    Description: VPC ID for environments

Resources:
  # Blueprint Configurations
  LakehouseCatalog:
    Type: AWS::DataZone::EnvironmentBlueprintConfiguration
    Properties:
      DomainIdentifier: !Ref DomainId
      EnvironmentBlueprintIdentifier: "LakehouseCatalog"
      ManageAccessRoleArn: !Ref ManageAccessRoleArn
      ProvisioningRoleArn: !Ref ProvisioningRoleArn
      RegionalParameters: [
        {
          Region: !Ref 'AWS::Region',
          Parameters: { }
        }
      ]
      EnabledRegions: [ !Ref 'AWS::Region' ]

  AmazonBedrockGuardrail:
    Type: AWS::DataZone::EnvironmentBlueprintConfiguration
    DependsOn: LakehouseCatalog
    Properties:
      DomainIdentifier: !Ref DomainId
      EnvironmentBlueprintIdentifier: "AmazonBedrockGuardrail"
      ManageAccessRoleArn: !Ref ManageAccessRoleArn
      ProvisioningRoleArn: !Ref ProvisioningRoleArn
      RegionalParameters: [
        {
          Region: !Ref 'AWS::Region',
          Parameters: {
            "S3Location": !Ref S3Location,
            "Subnets": !Ref Subnets,
            "VpcId": !Ref VpcId
          }
        }
      ]
      EnabledRegions: [ !Ref 'AWS::Region' ]

  MLExperiments:
    Type: AWS::DataZone::EnvironmentBlueprintConfiguration
    DependsOn: AmazonBedrockGuardrail
    Properties:
      DomainIdentifier: !Ref DomainId
      EnvironmentBlueprintIdentifier: "MLExperiments"
      ManageAccessRoleArn: !Ref ManageAccessRoleArn
      ProvisioningRoleArn: !Ref ProvisioningRoleArn
      RegionalParameters: [
        {
          Region: !Ref 'AWS::Region',
          Parameters: {
            "S3Location": !Ref S3Location,
            "Subnets": !Ref Subnets,
            "VpcId": !Ref VpcId
          }
        }
      ]
      EnabledRegions: [ !Ref 'AWS::Region' ]

  Tooling:
    Type: AWS::DataZone::EnvironmentBlueprintConfiguration
    DependsOn: MLExperiments
    Properties:
      DomainIdentifier: !Ref DomainId
      EnvironmentBlueprintIdentifier: "Tooling"
      ManageAccessRoleArn: !Ref ManageAccessRoleArn
      ProvisioningRoleArn: !Ref ProvisioningRoleArn
      RegionalParameters: [
        {
          Region: !Ref 'AWS::Region',
          Parameters: {
            "S3Location": !Ref S3Location,
            "Subnets": !Ref Subnets,
            "VpcId": !Ref VpcId
          }
        }
      ]
      EnabledRegions: [ !Ref 'AWS::Region' ]

  RedshiftServerless:
    Type: AWS::DataZone::EnvironmentBlueprintConfiguration
    DependsOn: Tooling
    Properties:
      DomainIdentifier: !Ref DomainId
      EnvironmentBlueprintIdentifier: "RedshiftServerless"
      ManageAccessRoleArn: !Ref ManageAccessRoleArn
      ProvisioningRoleArn: !Ref ProvisioningRoleArn
      RegionalParameters: [
        {
          Region: !Ref 'AWS::Region',
          Parameters: {
            "S3Location": !Ref S3Location,
            "Subnets": !Ref Subnets,
            "VpcId": !Ref VpcId
          }
        }
      ]
      EnabledRegions: [ !Ref 'AWS::Region' ]

  EmrServerless:
    Type: AWS::DataZone::EnvironmentBlueprintConfiguration
    DependsOn: RedshiftServerless
    Properties:
      DomainIdentifier: !Ref DomainId
      EnvironmentBlueprintIdentifier: "EmrServerless"
      ManageAccessRoleArn: !Ref ManageAccessRoleArn
      ProvisioningRoleArn: !Ref ProvisioningRoleArn
      RegionalParameters: [
        {
          Region: !Ref 'AWS::Region',
          Parameters: {
            "S3Location": !Ref S3Location,
            "Subnets": !Ref Subnets,
            "VpcId": !Ref VpcId
          }
        }
      ]
      EnabledRegions: [ !Ref 'AWS::Region' ]

  Workflows:
    Type: AWS::DataZone::EnvironmentBlueprintConfiguration
    DependsOn: EmrServerless
    Properties:
      DomainIdentifier: !Ref DomainId
      EnvironmentBlueprintIdentifier: "Workflows"
      ManageAccessRoleArn: !Ref ManageAccessRoleArn
      ProvisioningRoleArn: !Ref ProvisioningRoleArn
      RegionalParameters: [
        {
          Region: !Ref 'AWS::Region',
          Parameters: {
            "S3Location": !Ref S3Location,
            "Subnets": !Ref Subnets,
            "VpcId": !Ref VpcId
          }
        }
      ]
      EnabledRegions: [ !Ref 'AWS::Region' ]

  AmazonBedrockPrompt:
    Type: AWS::DataZone::EnvironmentBlueprintConfiguration
    DependsOn: Workflows
    Properties:
      DomainIdentifier: !Ref DomainId
      EnvironmentBlueprintIdentifier: "AmazonBedrockPrompt"
      ManageAccessRoleArn: !Ref ManageAccessRoleArn
      ProvisioningRoleArn: !Ref ProvisioningRoleArn
      RegionalParameters: [
        {
          Region: !Ref 'AWS::Region',
          Parameters: {
            "S3Location": !Ref S3Location,
            "Subnets": !Ref Subnets,
            "VpcId": !Ref VpcId
          }
        }
      ]
      EnabledRegions: [ !Ref 'AWS::Region' ]

  DataLake:
    Type: AWS::DataZone::EnvironmentBlueprintConfiguration
    DependsOn: AmazonBedrockPrompt
    Properties:
      DomainIdentifier: !Ref DomainId
      EnvironmentBlueprintIdentifier: "DataLake"
      ManageAccessRoleArn: !Ref ManageAccessRoleArn
      ProvisioningRoleArn: !Ref ProvisioningRoleArn
      RegionalParameters: [
        {
          Region: !Ref 'AWS::Region',
          Parameters: {
            "S3Location": !Ref S3Location,
            "Subnets": !Ref Subnets,
            "VpcId": !Ref VpcId
          }
        }
      ]
      EnabledRegions: [ !Ref 'AWS::Region' ]

  AmazonBedrockEvaluation:
    Type: AWS::DataZone::EnvironmentBlueprintConfiguration
    DependsOn: DataLake
    Properties:
      DomainIdentifier: !Ref DomainId
      EnvironmentBlueprintIdentifier: "AmazonBedrockEvaluation"
      ManageAccessRoleArn: !Ref ManageAccessRoleArn
      ProvisioningRoleArn: !Ref ProvisioningRoleArn
      RegionalParameters: [
        {
          Region: !Ref 'AWS::Region',
          Parameters: {
            "S3Location": !Ref S3Location,
            "Subnets": !Ref Subnets,
            "VpcId": !Ref VpcId
          }
        }
      ]
      EnabledRegions: [ !Ref 'AWS::Region' ]

  AmazonBedrockKnowledgeBase:
    Type: AWS::DataZone::EnvironmentBlueprintConfiguration
    DependsOn: AmazonBedrockEvaluation
    Properties:
      DomainIdentifier: !Ref DomainId
      EnvironmentBlueprintIdentifier: "AmazonBedrockKnowledgeBase"
      ManageAccessRoleArn: !Ref ManageAccessRoleArn
      ProvisioningRoleArn: !Ref ProvisioningRoleArn
      RegionalParameters: [
        {
          Region: !Ref 'AWS::Region',
          Parameters: {
            "S3Location": !Ref S3Location,
            "Subnets": !Ref Subnets,
            "VpcId": !Ref VpcId
          }
        }
      ]
      EnabledRegions: [ !Ref 'AWS::Region' ]

  PartnerApps:
    Type: AWS::DataZone::EnvironmentBlueprintConfiguration
    DependsOn: AmazonBedrockKnowledgeBase
    Properties:
      DomainIdentifier: !Ref DomainId
      EnvironmentBlueprintIdentifier: "PartnerApps"
      ManageAccessRoleArn: !Ref ManageAccessRoleArn
      ProvisioningRoleArn: !Ref ProvisioningRoleArn
      RegionalParameters: [
        {
          Region: !Ref 'AWS::Region',
          Parameters: {
            "S3Location": !Ref S3Location,
            "Subnets": !Ref Subnets,
            "VpcId": !Ref VpcId
          }
        }
      ]
      EnabledRegions: [ !Ref 'AWS::Region' ]

  AmazonBedrockChatAgent:
    Type: AWS::DataZone::EnvironmentBlueprintConfiguration
    DependsOn: PartnerApps
    Properties:
      DomainIdentifier: !Ref DomainId
      EnvironmentBlueprintIdentifier: "AmazonBedrockChatAgent"
      ManageAccessRoleArn: !Ref ManageAccessRoleArn
      ProvisioningRoleArn: !Ref ProvisioningRoleArn
      RegionalParameters: [
        {
          Region: !Ref 'AWS::Region',
          Parameters: {
            "S3Location": !Ref S3Location,
            "Subnets": !Ref Subnets,
            "VpcId": !Ref VpcId
          }
        }
      ]
      EnabledRegions: [ !Ref 'AWS::Region' ]

  AmazonBedrockFunction:
    Type: AWS::DataZone::EnvironmentBlueprintConfiguration
    DependsOn: AmazonBedrockChatAgent
    Properties:
      DomainIdentifier: !Ref DomainId
      EnvironmentBlueprintIdentifier: "AmazonBedrockFunction"
      ManageAccessRoleArn: !Ref ManageAccessRoleArn
      ProvisioningRoleArn: !Ref ProvisioningRoleArn
      RegionalParameters: [
        {
          Region: !Ref 'AWS::Region',
          Parameters: {
            "S3Location": !Ref S3Location,
            "Subnets": !Ref Subnets,
            "VpcId": !Ref VpcId
          }
        }
      ]
      EnabledRegions: [ !Ref 'AWS::Region' ]

  AmazonBedrockFlow:
    Type: AWS::DataZone::EnvironmentBlueprintConfiguration
    DependsOn: AmazonBedrockFunction
    Properties:
      DomainIdentifier: !Ref DomainId
      EnvironmentBlueprintIdentifier: "AmazonBedrockFlow"
      ManageAccessRoleArn: !Ref ManageAccessRoleArn
      ProvisioningRoleArn: !Ref ProvisioningRoleArn
      RegionalParameters: [
        {
          Region: !Ref 'AWS::Region',
          Parameters: {
            "S3Location": !Ref S3Location,
            "Subnets": !Ref Subnets,
            "VpcId": !Ref VpcId
          }
        }
      ]
      EnabledRegions: [ !Ref 'AWS::Region' ]

  EmrOnEc2:
    Type: AWS::DataZone::EnvironmentBlueprintConfiguration
    DependsOn: AmazonBedrockFlow
    Properties:
      DomainIdentifier: !Ref DomainId
      EnvironmentBlueprintIdentifier: "EmrOnEc2"
      ManageAccessRoleArn: !Ref ManageAccessRoleArn
      ProvisioningRoleArn: !Ref ProvisioningRoleArn
      RegionalParameters: [
        {
          Region: !Ref 'AWS::Region',
          Parameters: {
            "S3Location": !Ref S3Location,
            "Subnets": !Ref Subnets,
            "VpcId": !Ref VpcId
          }
        }
      ]
      EnabledRegions: [ !Ref 'AWS::Region' ]

  QuickSight:
    Type: AWS::DataZone::EnvironmentBlueprintConfiguration
    DependsOn: EmrOnEc2
    Properties:
      DomainIdentifier: !Ref DomainId
      EnvironmentBlueprintIdentifier: "QuickSight"
      ManageAccessRoleArn: !Ref ManageAccessRoleArn
      ProvisioningRoleArn: !Ref ProvisioningRoleArn
      RegionalParameters: [
        {
          Region: !Ref 'AWS::Region',
          Parameters: {
            "S3Location": !Ref S3Location,
            "Subnets": !Ref Subnets,
            "VpcId": !Ref VpcId
          }
        }
      ]
      EnabledRegions: [ !Ref 'AWS::Region' ]

  # Policy Grants - using Fn::ForEach to create grants for all blueprints
  'Fn::ForEach::PolicyGrants':
    - Blueprint
    - - !GetAtt LakehouseCatalog.EnvironmentBlueprintId
      - !GetAtt AmazonBedrockGuardrail.EnvironmentBlueprintId
      - !GetAtt MLExperiments.EnvironmentBlueprintId
      - !GetAtt Tooling.EnvironmentBlueprintId
      - !GetAtt RedshiftServerless.EnvironmentBlueprintId
      - !GetAtt EmrServerless.EnvironmentBlueprintId
      - !GetAtt Workflows.EnvironmentBlueprintId
      - !GetAtt AmazonBedrockPrompt.EnvironmentBlueprintId
      - !GetAtt DataLake.EnvironmentBlueprintId
      - !GetAtt AmazonBedrockEvaluation.EnvironmentBlueprintId
      - !GetAtt AmazonBedrockKnowledgeBase.EnvironmentBlueprintId
      - !GetAtt PartnerApps.EnvironmentBlueprintId
      - !GetAtt AmazonBedrockChatAgent.EnvironmentBlueprintId
      - !GetAtt AmazonBedrockFunction.EnvironmentBlueprintId
      - !GetAtt AmazonBedrockFlow.EnvironmentBlueprintId
      - !GetAtt EmrOnEc2.EnvironmentBlueprintId
      - !GetAtt QuickSight.EnvironmentBlueprintId
    - 'PolicyGrant&{Blueprint}':
        Type: AWS::DataZone::PolicyGrant
        Properties:
          DomainIdentifier: !Ref DomainId
          EntityType: ENVIRONMENT_BLUEPRINT_CONFIGURATION
          EntityIdentifier: !Sub '${ProjectAccountId}:${Blueprint}'
          PolicyType: CREATE_ENVIRONMENT_FROM_BLUEPRINT
          Detail:
            CreateEnvironmentFromBlueprint: {}
          Principal:
            Project:
              ProjectDesignation: CONTRIBUTOR
              ProjectGrantFilter:
                DomainUnitFilter:
                  DomainUnit: !Ref DomainUnitId
                  IncludeChildDomainUnits: true

Outputs:
  BlueprintCount:
    Description: Number of blueprints enabled
    Value: 17
