applicationName: DemoMarketingBundle
content: {}
stages:
  dev:
    stage: DEV
    domain:
      region: ${DEV_DOMAIN_REGION:us-east-1}
    project:
      name: dev-project-name
      create: false
  test:
    stage: TEST
    domain:
      region: ${DEV_DOMAIN_REGION:us-east-1}
    project:
      name: test-project-name
      create: false
    initialization:
      project:
        create: true
        profileName: All capabilities
        owners:
        - arn:aws:iam::123456789012:role/GitHubActionsRole-SMUS-CLI-Tests
        contributors: []
  prod:
    stage: PROD
    domain:
      region: ${DEV_DOMAIN_REGION:us-east-1}
    project:
      name: prod-project-name
      create: false
    initialization:
      project:
        create: true
        profileName: All capabilities
        owners:
        - arn:aws:iam::123456789012:role/GitHubActionsRole-SMUS-CLI-Tests
        contributors: []
