# Example: Environment Variable Parameterization
# This example demonstrates how to use environment variables in pipeline manifests
# for flexible multi-environment deployments.

pipelineName: ${PIPELINE_NAME:EnvironmentVariableExample}

# Domain configuration with environment variables
domain:
  name: ${DOMAIN_NAME:example-domain}
  region: ${AWS_REGION:us-east-1}

# Bundle configuration
bundle:
  bundlesDirectory: ${BUNDLES_DIR:./bundles}
  workflow:
    - connectionName: ${WORKFLOW_CONNECTION:default.s3_shared}
      append: true
      include: ['workflows/']
      exclude: ['.ipynb_checkpoints/', '__pycache__/', '*.pyc']
  storage:
    - connectionName: ${STORAGE_CONNECTION:default.s3_shared}
      append: false
      include: ['src/']
      exclude: ['.ipynb_checkpoints/', '__pycache__/', '*.pyc']

# Target environments with parameterized project names
targets:
  dev:
    stage: DEV
    default: true
    project:
      name: ${PROJECT_PREFIX:example}-dev-${TEAM_NAME:default}
    initialization:
      project:
        create: true
        profileName: 'All capabilities'
        owners: [${ADMIN_USER:Admin}]
      environments:
        - EnvironmentConfigurationName: 'Lakehouse Database'

  test:
    stage: TEST
    project:
      name: ${PROJECT_PREFIX:example}-test-${TEAM_NAME:default}
    initialization:
      project:
        create: true
        profileName: 'All capabilities'
        owners: [${ADMIN_USER:Admin}]
      environments:
        - EnvironmentConfigurationName: 'Lakehouse Database'

  prod:
    stage: PROD
    project:
      name: ${PROJECT_PREFIX:example}-prod-${TEAM_NAME:default}
    initialization:
      project:
        create: true
        profileName: 'All capabilities'
        owners: [${ADMIN_USER:Admin}]
      environments:
        - EnvironmentConfigurationName: 'Lakehouse Database'

# Workflows with parameterized connections
workflows:
  - workflowName: ${MAIN_WORKFLOW:example_workflow}
    connectionName: ${MWAA_CONNECTION:project.workflow_mwaa}
    triggerPostDeployment: ${TRIGGER_WORKFLOWS:true}
    logging: console
    engine: MWAA

# Usage Examples:
#
# 1. Local Development:
#    export AWS_REGION=us-west-2
#    export PROJECT_PREFIX=myteam
#    export TEAM_NAME=datascience
#    export ADMIN_USER=myuser
#    smus-cli deploy --pipeline environment-variables-example.yaml --target dev
#
# 2. CI/CD Environment:
#    export AWS_REGION=us-east-2
#    export PROJECT_PREFIX=production
#    export TEAM_NAME=platform
#    export DOMAIN_NAME=prod-datazone-domain
#    smus-cli deploy --pipeline environment-variables-example.yaml --target prod
#
# 3. Team-Specific Deployment:
#    export PROJECT_PREFIX=analytics
#    export TEAM_NAME=marketing
#    export ADMIN_USER=team-lead
#    # Results in project names like: analytics-dev-marketing, analytics-test-marketing, etc.
