name: Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        cd experimental/SMUS-CICD-pipeline-cli
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: |
        cd experimental/SMUS-CICD-pipeline-cli
        python -m build
    
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        cd experimental/SMUS-CICD-pipeline-cli
        twine upload dist/*
