# GenAI Workflow Example - Unified IAM role setup
# Testing STS caller identity logging
applicationName: IntegrationTestGenAIWorkflow
content:
  storage:
  - name: agent-code
    include:
    - job-code
  - name: genai-workflows
    include:
    - workflows
  workflows:
  - workflowName: genai_dev_workflow
    connectionName: default.workflow_serverless
stages:
  dev:
    stage: DEV
    domain:
      tags:
        purpose: smus-cicd-testing
      region: ${DEV_DOMAIN_REGION:us-east-2}
    project:
      name: dev-marketing
    environment_variables:
      S3_PREFIX: dev
  test:
    stage: TEST
    domain:
      tags:
        purpose: smus-cicd-testing
      region: ${TEST_DOMAIN_REGION:us-east-1}
    project:
      name: test-marketing
      owners:
      - Eng1
      - arn:aws:iam::${AWS_ACCOUNT_ID}:role/GitHubActionsRole-SMUS-CLI-Tests
      - arn:aws:iam::${AWS_ACCOUNT_ID}:role/Admin
    environment_variables:
      S3_PREFIX: test
    deployment_configuration:
      storage:
      - name: agent-code
        connectionName: default.s3_shared
        targetDirectory: genai/bundle/agent-code
      - name: genai-workflows
        connectionName: default.s3_shared
        targetDirectory: genai/bundle/workflows
    # bootstrap:
    #   actions:
    #   - type: workflow.create
    #     workflowName: genai_dev_workflow
    #   - type: workflow.run
    #     workflowName: genai_dev_workflow
    #     trailLogs: true
tests:
  folder: examples/analytic-workflow/genai/app_tests/






# Trigger workflow
